### ISSUE TITLE
Question - Is it possible to download synthetic sequences (taxid 81077) with ngd

### ISSUE THREAD

**Issue by jagos01** [kblin/ncbi-acc-download#18]
Hello,
This script has worked great for downloading many sequences.  However, I am now trying to download synthetic sequences (taxid 81077).  I used gimme_taxa.py -j -o /synthetic.txt 81077 to create a file with all descendent taxids.  The problem is these synthetic sequences do not fall into a group supported by ngd.  The lineage is - other sequences; artificial sequences.   Can ngd be used to download these sequences?  If not is there an easy way to download them?
Thanks,

**Comment by kblin** [comment]
Hi, shouldn't this be a feature request at https://github.com/kblin/ncbi-genome-download ?

**Comment by jagos01** [comment]
Yes you are correct. I had two tabs open and posted in the wrong one.  I will post in the correct repository.
Thanks,
