### ISSUE TITLE
The -F gff3 output has no header

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-acc-download#5]
This isn't really your problem, as I assume you just copy what NCBI gives you, but the `-F gff3` result doesn't have a header which I think is needed to validate?

```
 ##gff-version 3
```

**Comment by kblin** [comment]
Yes, I'm copying what the NCBI API provides, character by character.

**Comment by kblin** [comment]
That said, I'm not currently trying to validate GFF files, as validation right now is just checking if Biopython will load the file.

**Comment by tseemann** [comment]
Does biopython auto-detect the GFF version number?
Or are you just getting lucky because GFF3 is standard now?

**Comment by kblin** [comment]
Cleaning up old issues. `ncbi-acc-download` doesn't validate GFF files at all because Biopython doesn't support the file format.
